Algoritmo "EXERCICIO 2"

Var

v1, v2, v3 : vetor [0..9] de inteiro
cont : inteiro

Inicio
   escreval (" ESCREVA O VETOR 1 ")
   escreval ()
 para cont de 0 ate 3 faca
   escreva (" vetor 1 = ")
     leia (v1[cont])
 fimpara
  escreval ()
escreval (" COPIA PARA VETOR 2 ")
  escreval ()
 para cont de 0 ate 3 faca
    v2[cont] <- (v1[cont])
  escreval (" vetor 2 = ",v2[cont],"")
 fimpara

Fimalgoritmo