Algoritmo "Programa 1."
 // Algoritmo de do nome e sobre nome
Var
 nome: caracter
 sobrenome: caracter

Inicio
// 1.a
 escreval ()
 escreval (" Qual é seu nome?")
 escreval ()
 leia (nome)
// 1.b
 escreval ()
 escreval (" Qual é seu sobrenome?")
 escreval ()
 leia (sobrenome)
// 1.c
 escreval ()
 escreval (" Seu nome completo é: ", nome, " ", sobrenome)
 escreval ()
// 1.d - O nome completo esta na c
Fimalgoritmo